### ISSUE TITLE
HTML Development

### ISSUE THREAD

**Issue by clucasalcantara** [workwith-coffee/portal#1]
Add a static version in HTML of our current layout while we are kickstarting the frontend boilerplate.

The HTML should be used to mount our react components.

![image](https://user-images.githubusercontent.com/6919712/51617936-2b2aff80-1f25-11e9-9760-4867db8c5195.png)

**Comment by caiojhonny** [comment]
Static template homepage done ✅
[workwithcoffee-static.zip](https://github.com/workwith-coffee/portal/files/2792027/workwithcoffee-static.zip)
