### ISSUE TITLE
Portal static v1.0

### ISSUE THREAD

**Issue by clucasalcantara** [workwith-coffee/portal#16]
@mvfsillva @rafaelverger Vocês conseguem me ajudar com o desenvolvimento de uma estática html css desse modelo abaixo?

![2fdf81ee-0a83-40a0-be0f-4f1e1dd4b757](https://user-images.githubusercontent.com/6919712/35473455-da5d0a80-0378-11e8-803f-4556ab92e7a9.jpeg)

**Comment by mvfsillva** [comment]
Sim, consigo 👍

**Comment by clucasalcantara** [comment]
Guys, dividi essa issue por section e pus os labels direitinho com as imagens para desenvolvimento.

Criei tb o milestone do MVP.

Tkx for the help <3
